version: '2'
services:
  web:
    image: nginx
    container_name: nextcloud_webserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST=<my_virtualhost>
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=<my_hostname>
      - LETSENCRYPT_EMAIL=<my_mail>
    networks:
      - traefik 
      - default 
    labels:
      - "traefik.backend=backup"
      - "traefik.frontend.rule=Host:<my_hostname>"
      - "traefik.frontend.port=80"
      - "traefik.docker.network=traefik_default"
    restart: always

  app:
    image: nextcloud:fpm
    container_name: nextcloud_fpm
    links:
      - db
    volumes:
      - ./nextcloud/apps:/var/www/html/apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
      - ./nextcloud/core/skeleton:/var/www/html/core/skeleton
    networks:
      - default
    labels:
      - "traefik.enable=false"
    restart: always

  db:
    image: mariadb
    container_name: db
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    networks:
      - default 
    labels:
      - "traefik.enable=false"
    restart: always

  redis:
    image: redis
    container_name: redis
    networks:
      - default 
    labels:
      - "traefik.enable=false"
    restart: always

networks:
  traefik:
    external:
      name: traefik_default
